server:
  port: 7777
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
  
spring:
  application:
    name: ecommerce-api-gatway
  cloud:
    gateway:
      routes:
      - id: bank
        uri: lb://bank-service
          #http://localhost:1020/
        predicates:
        - Path=/bankapp/**
      - id: ecommerce
        uri: lb://ecommerce-service
          #http://localhost:1010/
        predicates:
        - Path=/shopping/**